name: '      A fly went by'
favicon: null
layout_spectrum: 0.28482
typography_spectrum: 0.13393109035678208
title: Technology with Soul
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#050308'
    - '#7d4223'
    - '#a8ac9f'
    - '#c5733e'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
